#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# hw.tcl: Tcl script for re-creating project 'hw'
#
# Generated by Vivado on Tue Dec 09 10:38:14 CST 2025
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (hw.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/archive_project_summary.txt"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/MouseCtl.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/MouseDisplay.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/Ps2Interface.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/UART_TX_CTRL.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/clk_wiz_0.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/clk_wiz_0_clk_wiz.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/debouncer.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/vga_ctrl.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/sources_1/imports/hdl/GPIO_Demo.vhd"
#    "/home/david/Downloads/Basys-3-GPIO-hw2025/hw.srcs/constrs_1/imports/constraints/Basys3_Master.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Load modules (relative path)
set script_dir [file dirname [info script]]
source [file join $script_dir tcl/help.tcl]
source [file join $script_dir tcl/config.tcl]
source [file join $script_dir tcl/fileset.tcl]
source [file join $script_dir tcl/project_props.tcl]

# Create project and set properties
create_project $::config::xilinx_proj_name "./$::config::xilinx_proj_name" -part $::config::fpga_part_name
set ::proj_dir [get_property directory [current_project]]
set_project_properties $::proj_dir $::config::xilinx_proj_name $::config::fpga_part_name $::config::default_lib

# sources_1
set fs_sources [ensure_and_import_vhdl2008_fileset sources_1 -srcset $::files::vhdl_rel_files]
safe_set_property "top" $::config::top_source_name $fs_sources

# import IP file and set its properties
# import_ip_into_sources $fs_sources $::files::ip_file

# constrs_1
set fs_constrs [ensure_and_import_fileset constrs_1 -constrset [list $::files::xdc_file]]
safe_set_property "target_part" $::config::fpga_part_name $fs_constrs

# sim_1
set fs_sim [ensure_and_import_vhdl2008_fileset sim_1 -simset [list $::files::tb_file]]
safe_set_property "sim_wrapper_top" "1" $fs_sim
safe_set_property "top" $::config::top_tb_name $fs_sim
safe_set_property "top_lib" $::config::default_lib $fs_sim

update_compile_order -fileset sources_1
