set_property SRC_FILE_INFO {cfile:/home/david/r09522848/vivado2024/coraz707s_baremetal_0905/coraz707s_baremetal_0905.srcs/constrs_1/imports/digilent-xdc-master/Cora-Z7-07S-Master.xdc rfile:../../../coraz707s_baremetal_0905.srcs/constrs_1/imports/digilent-xdc-master/Cora-Z7-07S-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D20   IOSTANDARD LVCMOS33 } [get_ports { btn_tri_io[0] }]; #IO_L4N_T0_35 Sch=btn[0]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { btn_tri_io[1] }]; #IO_L4P_T0_35 Sch=btn[1]
